### ISSUE TITLE
Save view not working

### ISSUE THREAD

**Issue by johnsone006** [gavrant/nifskope#4]
Title says it all.

**Comment by gavrant** [comment]
Does this mean that NifSkope does not save the size and position of the main window and its UI controls between runs (or saves them incorrectly) **WHEN** it's run by your UI automation tools like SAP or NifSorter?

**Comment by johnsone006** [comment]
1. No. It means the Save View button doesn't work. 
2. Actually, before I installed some updates to my computer, sometimes it would do that even when I didn't use NifSorter or ui automation tools. It just annoyed me the most when it would be inconsistent while using NifSorter or SAP because those two programs open and close NifSkope automatically, so whenever it would go in Normal mode or whatever and then close, it would open the same way. It hasn't been misbehaving (besides the Save View button not working) since those updates, though, so I suspect it was caused by my computer and not the code you made. Would you like me to let you know if it happens again?

**Comment by gavrant** [comment]
Render -> Save View works fine in pair with Render -> Load View, at least for me. That is, you need to click Load View to apply the last saved view.

**Comment by johnsone006** [comment]
I don't think you are understanding me, gavrant. When I click the Save View button- not the menu item, the button that is always visible, as long as the render toolbar is enabled-nothing happens. I tried clicking it, closing the window, reopening the same nif, and then clicking load view just to make sure that the Save View button just wasn't getting highlighted. Nope. It didn't work. Edit: I'm glad you mentioned that, however, because it does seem like the menu item is working. Thanks for telling me.

**Comment by gavrant** [comment]
The video below shows how opening NifSkope and clicking "Load Saved View" on the toolbar works for me. For you it does not behave that way? Or do you click/expect something else?

https://github.com/user-attachments/assets/6bf9af8b-3adb-4b75-8f59-86956cced8af

**Comment by johnsone006** [comment]
Yeah, you misunderstand me. The button that looks like the eye without the pencil works fine. Its the button that looks like an eye thats overlapped by a pencil without an eraser that's not working. This one: 
![image](https://github.com/user-attachments/assets/735ed2dc-ce6c-4bdd-b6ef-ccc8fec968c0)

**Comment by johnsone006** [comment]
Wait a minute. It did just work for the file arfloor03broken.nif. What I mean by that is the Save view checkbox (the thing that looks like an eye with a pencil) didn't appear to get selected, but once I closed the .nif, reopened it, and clicked the Load view, it did load the view I saved. Huh. But I'm sure it didn't do it for a different file because I remember checking. 

In any case, the save view checkbox remains visually unchanged when clicked.

**Comment by johnsone006** [comment]
So I mispoke again; therefore, I have decided to just record a video of what I mean. The first NifSkope shown is dev 7, the next is yours. 

https://github.com/user-attachments/assets/b3c5ceb3-0fc6-4ec3-af93-b2e2d45d988e

**Comment by gavrant** [comment]
Oh, so in other words, this ticket means: "Load Saved View" button (both on the toolbar and in the menu) not get auto-checked when you click "Save View"? I'll fix that, but don't you agree that it's pretty far off from the original "Save view not working / Title says it all"? :D

**Comment by johnsone006** [comment]
Indeed, that's why I used the video. However, I maintain that prior to creating this issue, it wasn't working. I followed these steps in your version: 
1. Open a .nif (I honestly can't remember which .nif it was, which is unfortunate because I suspect that matters)
2. Change the view from the default.
3. Click save view. Notice that nothing about the UI changed visually.
4. Close the .nif
5. Open that exact same nif
6. click Load View
7. Notice that nothing changed.
That was back when I had Dev 8 on my machine still, though. I took it off because it wouldn't let me make your version be the default program to open .nif files. Yes, I am 100% positive that I both chose your version as the default *and* that it still used Dev 8 as the default. I know it was dev 8 because the word gavrant was nowhere to be seen in the titlebar. Think these things are related?

**Comment by gavrant** [comment]
I can tell that "Save View" is compatible between Dev 7 and Dev 9c in the sense that views saved in Dev 7 work in Dev 9c too, and vice versa. Don't know about Dev 8 though.

**Comment by gavrant** [comment]
Let's do the following: in the commit above, I did make "Load View" (both of them) getting "checked" state when "Save View" (any of them) is clicked, and I'll make a release with this fix in a few days. Meanwhile, if you stumble upon some other misbehavior of "Load/Save View", you'll just create a new issue. It's not like we are on a tight budget for issue tickets :)

**Comment by johnsone006** [comment]
Just so you know, gavrant, I will need the actual file. I do not have the program this is made from on my machine, nor do I know how to use it

**Comment by gavrant** [comment]
I just made a proper release, with this fix included: https://github.com/gavrant/nifskope/releases

**Comment by johnsone006** [comment]
Hey, so I downloaded that version, but Microsoft SmartScreen is preventing it from running. Do you have any idea why?
Edit: nvm, I have a theory about why its doing this. Nothing to be worried about.

**Comment by gavrant** [comment]
Antiviruses (Microsoft ones especially?) like to complain about files from github shortly after those files' release. The complaints usually go away in a few days, when the antivirus updates its databases. If you are not sure, you can verify the download URL of a file on a 3rd party site like [VirusTotal](https://www.virustotal.com/).
