### ISSUE TITLE
Cannot load BSSkyShaderProperty

### ISSUE THREAD

**Issue by johnsone006** [gavrant/nifskope#6]
This time, I took screenshots for record purposes so there's no confusion. I tried to open this same nif with both Dev 7 and yours; I've included both screenshots. 
![image](https://github.com/user-attachments/assets/a6e4c20f-9a72-46fd-ae28-e0442448fea0)
![image](https://github.com/user-attachments/assets/7054ab74-7827-4b4c-b751-3e5687ec63db)

**Comment by johnsone006** [comment]
I have found another one that has that same issue. Would you like me to keep a list of the .nifs that have that error and give it to you?

**Comment by gavrant** [comment]
No need, I have enough diagnostics info.
